/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Setting;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

import configs.AppConfig;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionEvent;

/**
 *
 * @author TRUNG HÒA
 */
public class JpSetting extends javax.swing.JPanel {

    /**
     * Creates new form JpSetting
     */
    public JpSetting() {
        initComponents();
        JpPaneSetting.removeAll();
        JpPaneSetting.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnThongTin = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        JpPaneSetting = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1255, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(1255, 500));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThongTin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnThongTin.setForeground(new java.awt.Color(51, 0, 51));
        btnThongTin.setIcon(new ImageIcon(AppConfig.getImageURL("info.png"))); // NOI18N
        btnThongTin.setText("THÔNG TIN");
        btnThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongTin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongTin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThongTin.setIconTextGap(7);
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(51, 0, 51));
        btnCapNhat.setIcon(new ImageIcon(AppConfig.getImageURL("update.png"))); // NOI18N
        btnCapNhat.setText("ĐỔI MẬT KHẨU");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCapNhat.setIconTextGap(7);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnCapNhat, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        				.addComponent(btnThongTin, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnCapNhat)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnThongTin)
        			.addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        JpPaneSetting.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JpPaneSetting.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpPaneSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpPaneSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        
        JLabel lblNewLabel = new JLabel("");
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Tài liệu\\Hình ảnh\\DoAnCoSo\\setting.png"));
        JpPaneSetting.add(lblNewLabel, BorderLayout.NORTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        JpThongTin tt = new JpThongTin();
            JpPaneSetting.removeAll();
            JpPaneSetting.add(tt);
            JpPaneSetting.revalidate();
            
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        JpDoiMk dmk = new JpDoiMk();
        JpPaneSetting.removeAll();
        JpPaneSetting.add(dmk);
        JpPaneSetting.updateUI();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpPaneSetting;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
}
